/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Connection.Connector;
import Controllers.SalaryDetailsController;
import Controllers.SalarySheduleController;
import Controllers.StaffController;
import Pojos.SalaryDetails;
import Pojos.SalaryShedule;
import Pojos.Staff;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;


public class SalaryDetailsView extends javax.swing.JFrame {

    /**
     * Creates new form SalaryDetailsView
     */
    public SalaryDetailsView() {
        initComponents();
        loadStaffIDs();
        loadTable();
    }

    private void resetForm() {
        id.setText("0");
        working_days.setText("");
        over_time_hrs.setText("");
        advance.setText("");
    }
    
    private void serchDataFromTable(String s) {
        DefaultTableModel dtm = (DefaultTableModel) this.table.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(dtm);
        table.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(s));
    }

    private void loadTable() {

        List<SalaryDetails> details = null;
        try {
            details = SalaryDetailsController.getInstance().serchSalaryDetails();

        } catch (Exception ex) {
//            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel but_dt = (DefaultTableModel) this.table.getModel();
        but_dt.setRowCount(0);

        for (int i = 0; i < details.size(); i++) {
            Vector v = new Vector();
            SalaryDetails ss = details.get(i);
            try {
                SalaryShedule s = SalarySheduleController.getInstance().serchSalaryDetailsByID(ss.getStaffId());

                v.add(ss.getSalaryDetailsId());
                v.add(ss.getStaffId());
                v.add(ss.getNoOfWorkingDays());
                v.add(s.getBasicSalary());
                v.add(ss.getNoOfWorkingDays() * Math.round(s.getBasicSalary() / 25));
                v.add(ss.getNoOfWorkingDays() * Math.round(100));
                v.add(ss.getNoOfWorkingDays() * Math.round(40));
                v.add(ss.getOverTimeHrs());
                v.add(s.getOverTimeAmount());
                v.add(s.getOverTimeAmount() * ss.getOverTimeHrs());
                v.add(s.getAllowns());
                v.add(s.getAllowns() + s.getOverTimeAmount() * ss.getOverTimeHrs() + ss.getNoOfWorkingDays() * Math.round(s.getBasicSalary() / 25) + ss.getNoOfWorkingDays() * 140);
                v.add((Math.round(s.getBasicSalary() / 25) + ss.getNoOfWorkingDays() * 140) * 0.08);
                v.add(ss.getAdvance());
                v.add((s.getAllowns() + s.getOverTimeAmount() * ss.getOverTimeHrs() + ss.getNoOfWorkingDays() * Math.round(s.getBasicSalary() / 25) + ss.getNoOfWorkingDays() * 140) - ((Math.round(s.getBasicSalary() / 25) + ss.getNoOfWorkingDays() * 140) * 0.08) - ss.getAdvance());
                v.add(ss.getMonth());

                but_dt.addRow(v);
            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(this, "First try to set Salary for employee");
                SalarySheduleView obj = new SalarySheduleView();
                obj.setVisible(true);
                this.dispose();
            }

        }
    }

    public void loadStaffIDs() {
        List<Staff> details = null;
        try {
            details = StaffController.getInstance().serchStaffDetails();

        } catch (Exception ex) {
//            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (int i = 0; i < details.size(); i++) {
            staff_id.addItem(details.get(i).getEmployeeId() + "");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        staff_id = new javax.swing.JComboBox<>();
        advance = new javax.swing.JTextField();
        working_days = new javax.swing.JTextField();
        over_time_hrs = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        id = new javax.swing.JTextField();
        month = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        searchbar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Attendance Management");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Attendance Management");

        advance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                advanceKeyTyped(evt);
            }
        });

        working_days.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                working_daysKeyTyped(evt);
            }
        });

        over_time_hrs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                over_time_hrsKeyTyped(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Select Staff ID");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("No of Working Days");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Over Time Hrs");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Advance");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/i_delete.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/i_save.png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/i_edit.png"))); // NOI18N
        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Saff ID", "Worked Days", "Per Day", "Total Salary", "BRA1", "BRA2", "OT hrs", "OT Rate", "OT Amount", "Allowns", "Gross Salary", "EPF 08%", "Advance", "Net Salary", "Month"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(3).setResizable(false);
        }

        id.setEditable(false);
        id.setBackground(new java.awt.Color(255, 255, 255));
        id.setForeground(new java.awt.Color(0, 0, 0));
        id.setText("0");

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/i_view_page.png"))); // NOI18N
        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        searchbar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchbarKeyReleased(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/i_search_1.png"))); // NOI18N

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/i_report.png"))); // NOI18N
        jButton5.setText("Attemdance Report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("MONTHLY REPORT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(513, 513, 513)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(working_days)
                            .addComponent(staff_id, 0, 359, Short.MAX_VALUE)
                            .addComponent(over_time_hrs, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(advance, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(month, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(searchbar)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)))
                        .addGap(89, 89, 89))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {advance, over_time_hrs, searchbar, staff_id, working_days});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staff_id, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(working_days, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(over_time_hrs, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(advance, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {advance, jButton1, jButton2, jButton3, jButton5, jButton6, month, over_time_hrs, searchbar, staff_id, working_days});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1317, 747));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (id.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "Please select row to update");
        } else {
            if (JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this?", "Delete Row", JOptionPane.YES_NO_OPTION) == 0) {
                SalaryDetails ss = new SalaryDetails();
                ss.setSalaryDetailsId(Integer.parseInt(id.getText()));
                ss.setStaffId(Integer.parseInt(staff_id.getSelectedItem().toString()));
                ss.setMonth(month.getSelectedItem().toString());
                ss.setNoOfWorkingDays(Double.parseDouble(working_days.getText()));
                ss.setOverTimeHrs(Double.parseDouble(over_time_hrs.getText()));
                ss.setAdvance(Double.parseDouble(advance.getText()));

                SalaryDetailsController.getInstance().deleteSalaryDetails(ss);
                table.removeAll();
                loadTable();
                resetForm();
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (id.getText().isEmpty() || working_days.getText().isEmpty() || over_time_hrs.getText().isEmpty() || advance.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill form");
        } else {
            SalaryDetails ss = new SalaryDetails();
            ss.setSalaryDetailsId(Integer.parseInt(id.getText()));
            ss.setStaffId(Integer.parseInt(staff_id.getSelectedItem().toString()));
            ss.setMonth(month.getSelectedItem().toString());
            ss.setNoOfWorkingDays(Double.parseDouble(working_days.getText()));
            ss.setOverTimeHrs(Double.parseDouble(over_time_hrs.getText()));
            ss.setAdvance(Double.parseDouble(advance.getText()));

            SalaryDetailsController.getInstance().addSalaryDetails(ss);
            table.removeAll();
            loadTable();
            resetForm();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (id.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "Please select row to update");
        } else if (id.getText().isEmpty() || working_days.getText().isEmpty() || over_time_hrs.getText().isEmpty() || advance.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill form");
        } else {

            SalaryDetails ss = new SalaryDetails();
            ss.setSalaryDetailsId(Integer.parseInt(id.getText()));
            ss.setStaffId(Integer.parseInt(staff_id.getSelectedItem().toString()));
            ss.setMonth(month.getSelectedItem().toString());
            ss.setNoOfWorkingDays(Double.parseDouble(working_days.getText()));
            ss.setOverTimeHrs(Double.parseDouble(over_time_hrs.getText()));
            ss.setAdvance(Double.parseDouble(advance.getText()));

            SalaryDetailsController.getInstance().updateSalaryDetails(ss);
            table.removeAll();
            loadTable();
            resetForm();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

        DefaultTableModel dtm = (DefaultTableModel) this.table.getModel();
        int sr = table.getSelectedRow();

        id.setText(dtm.getValueAt(sr, 0).toString());
        staff_id.setSelectedItem(dtm.getValueAt(sr, 1).toString());
        month.setSelectedItem(dtm.getValueAt(sr, 15).toString());
        working_days.setText(dtm.getValueAt(sr, 2).toString());
        over_time_hrs.setText(dtm.getValueAt(sr, 7).toString());
        advance.setText(dtm.getValueAt(sr, 13).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Home obj = new Home();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void working_daysKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_working_daysKeyTyped
        char c = evt.getKeyChar();

        if (working_days.getText().contains(".")) {
            if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {

                evt.consume();
            }
        } else {
            if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE || c == '.')) {

                evt.consume();
            }
        }
    }//GEN-LAST:event_working_daysKeyTyped

    private void over_time_hrsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_over_time_hrsKeyTyped
        char c = evt.getKeyChar();

        if (over_time_hrs.getText().contains(".")) {
            if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {

                evt.consume();
            }
        } else {
            if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE || c == '.')) {

                evt.consume();
            }
        }
    }//GEN-LAST:event_over_time_hrsKeyTyped

    private void advanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_advanceKeyTyped
        char c = evt.getKeyChar();

        if (advance.getText().contains(".")) {
            if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {

                evt.consume();
            }
        } else {
            if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE || c == '.')) {

                evt.consume();
            }
        }
    }//GEN-LAST:event_advanceKeyTyped

    private void searchbarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbarKeyReleased
        serchDataFromTable(searchbar.getText());
    }//GEN-LAST:event_searchbarKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Connector a = new Connector();

        String report = "D:\\PROFESSIONAL SOFTWARE DEVELOPMENT\\SLIIT JUNIOR PROJECTS\\2020\\HRM_SYSTEM\\src\\Reports\\AttendanceReport.jrxml";
        try {
            JasperReport jr = JasperCompileManager.compileReport(report);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, a.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(SalarySheduleView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(SalarySheduleView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Connector a = new Connector();

        String report = "D:\\PROFESSIONAL SOFTWARE DEVELOPMENT\\SLIIT JUNIOR PROJECTS\\2020\\HRM_SYSTEM\\src\\Reports\\AttendanceReport2.jrxml";
        try {
            JasperReport jr = JasperCompileManager.compileReport(report);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, a.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(SalarySheduleView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(SalarySheduleView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaryDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaryDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaryDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaryDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaryDetailsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField advance;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField over_time_hrs;
    private javax.swing.JTextField searchbar;
    private javax.swing.JComboBox<String> staff_id;
    private javax.swing.JTable table;
    private javax.swing.JTextField working_days;
    // End of variables declaration//GEN-END:variables

}
