package Pojos;
// Generated Mar 14, 2020 5:08:16 PM by Hibernate Tools 4.3.1



/**
 * SalaryDetails generated by hbm2java
 */
public class SalaryDetails  implements java.io.Serializable {


     private Integer salaryDetailsId;
     private String month;
     private Integer staffId;
     private Double noOfWorkingDays;
     private Double overTimeHrs;
     private Double advance;

    public SalaryDetails() {
    }

    public SalaryDetails(String month, Integer staffId, Double noOfWorkingDays, Double overTimeHrs, Double advance) {
       this.month = month;
       this.staffId = staffId;
       this.noOfWorkingDays = noOfWorkingDays;
       this.overTimeHrs = overTimeHrs;
       this.advance = advance;
    }
   
    public Integer getSalaryDetailsId() {
        return this.salaryDetailsId;
    }
    
    public void setSalaryDetailsId(Integer salaryDetailsId) {
        this.salaryDetailsId = salaryDetailsId;
    }
    public String getMonth() {
        return this.month;
    }
    
    public void setMonth(String month) {
        this.month = month;
    }
    public Integer getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }
    public Double getNoOfWorkingDays() {
        return this.noOfWorkingDays;
    }
    
    public void setNoOfWorkingDays(Double noOfWorkingDays) {
        this.noOfWorkingDays = noOfWorkingDays;
    }
    public Double getOverTimeHrs() {
        return this.overTimeHrs;
    }
    
    public void setOverTimeHrs(Double overTimeHrs) {
        this.overTimeHrs = overTimeHrs;
    }
    public Double getAdvance() {
        return this.advance;
    }
    
    public void setAdvance(Double advance) {
        this.advance = advance;
    }




}


